bolero-generator/src/lib.rs, bolero-generator/src/one_of.rs
This adds `one_of` and `one_value_of` functionality for selecting between multiple generators and values, respectively.
```rust
// Array
one_of([gen(), gen(), gen()]);
one_value_of([1, 2, 3]);
// Array with OneOfExt
[gen(), gen(), gen()].one_of();
[1, 2, 3].one_value_of();
// Tuple (allows different generator types to be used)
one_of((gen(), 0..4, 7..30));
(gen(), 0..4, 7..30).one_of();
```
=> generator: add one_of

.gitignore, bolero-engine/src/shrink.rs
In investigating #18 I found an issue with the `apply_remove_chunk` shrinker that would leave the input in a state that would not panic and end up with an empty message. I've added some checks to the shrinkers to make sure this doesn't happen, or if it does, it'll at least show what happened.
=> engine: fix invalid shrink transforms

README.md, bolero/Cargo.toml, bolero/src/lib.rs, book/src/cli-installation.md, book/src/features/input-shrinking.md, book/src/features/private-testing.md, book/src/features/structured-testing.md, book/src/introduction.md, book/src/tutorials/fibonacci.md, cargo-bolero/README.md, cargo-bolero/src/new.rs, cargo-bolero/src/test.rs, cargo-bolero/tests/fuzz_bytes/fuzz_target.rs, cargo-bolero/tests/fuzz_generator/fuzz_target.rs, examples/basic/src/lib.rs, examples/basic/tests/fuzz_bytes/fuzz_target.rs, examples/basic/tests/fuzz_generator/fuzz_target.rs, examples/basic/tests/fuzz_operations/fuzz_target.rs, examples/basic/tests/other.rs, examples/workspace/crate_a/src/lib.rs, examples/workspace/crate_a/tests/fuzz_a/fuzz_target.rs, examples/workspace/crate_b/src/lib.rs, examples/workspace/crate_b/tests/fuzz_b/fuzz_target.rs
With the end goal of `bolero` becoming a front-end for various types of execution engines outside of fuzzing (e.g. [crux](https://github.com/camshaft/bolero/issues/34), [seer](https://github.com/dwrensha/seer), [haybale](https://github.com/PLSysSec/haybale), etc) we're deprecating `fuzz!` in favor of the previously-removed `check!`. The API stays exactly the same.
=> deprecate fuzz! in favor of check!

book/src/features/rust-stable.md, cargo-bolero/src/project.rs
A sanitizer is really needed in order to get good results so this should be the default. Users can always opt out with `--sanitizer NONE`
=> default to --sanitizer address

bolero/Cargo.toml
This only contains a trivial change:
<https://github.com/alexcrichton/cfg-if/pull/37>
Sending this to prevent duplicate versions of cfg-if in dependency trees.
=> Update to cfg-if 1

bolero-generator-derive/Cargo.toml, bolero-generator-derive/src/generator_attr.rs, bolero-generator-derive/src/lib.rs, bolero-generator/src/bool.rs, bolero-generator/src/std/mod.rs
We were using a private module from syn rather than importing proc-macro2 directly.
=> generator-derive: use proc-macro2 directly

.github/workflows/main.yml, bolero-afl/src/lib.rs, bolero-engine/src/lib.rs, bolero-engine/src/rng.rs, bolero-engine/src/shrink.rs, bolero-engine/src/test.rs, bolero-generator/src/atomic.rs, bolero-generator/src/bool.rs, bolero-generator/src/bounded.rs, bolero-generator/src/char.rs, bolero-generator/src/driver.rs, bolero-generator/src/driver/bytes.rs, bolero-generator/src/driver/macros.rs, bolero-generator/src/driver/rng.rs, bolero-generator/src/lib.rs, bolero-generator/src/num.rs, bolero-generator/src/uniform.rs, bolero-honggfuzz/src/lib.rs, bolero-libfuzzer/src/lib.rs, bolero/src/lib.rs, bolero/src/test/mod.rs
while wiring up RMC support, it was discovered that it would be better to remove the ability to generate bytes on arbitrary slices and leave primitive value generate up to the actual driver.
=> make the driver interface less aware of input representation

cargo-bolero/Cargo.toml, cargo-bolero/src/engine.rs, cargo-bolero/src/main.rs, cargo-bolero/src/rmc.rs, cargo-bolero/src/selection.rs
Added `rmc` as an option for `cargo bolero test`'s `--engine` option. The engine executes `cargo rmc` with the provided test function under the hood.
=> Added --engine rmc

bolero-generator/src/range.rs, cargo-bolero/Cargo.toml, cargo-bolero/src/engine.rs, cargo-bolero/src/kani.rs, cargo-bolero/src/main.rs
RMC has been renamed to Kani. This PR updates any references to RMC to instead refer to Kani.
=> Renamed RMC to Kani

cargo-bolero/src/kani.rs
Update `cargo kani` args:
1. Replace deprecated `--function` option with `--harness`
2. Remove unneeded `--cbmc-args --object-bits 16` which is now the default for `cargo kani`
3. Add `--tests`
=> Update cargo kani args

.github/workflows/main.yml, examples/basic/Cargo.toml, examples/basic/src/lib.rs
Remove hack of adding `bolero` as a dependency for Kani, which is no longer needed.
Also, run kani in CI via `cargo bolero test --engine kani`, which is the documented method of running Kani.
=> Remove bolero from kani dependencies

cargo-bolero/src/engine.rs, cargo-bolero/src/list.rs, cargo-bolero/src/main.rs, cargo-bolero/src/project.rs, cargo-bolero/src/selection.rs
Print all the causes with {:#} formatter and replace .unwrap() with ?.
When `cargo bolero test` is run, previously the error due to missing rustup was
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }'
```
Now the error is:
```
error: failed to determine nightly toolchain version: No such file or directory (os error 2)
```
This way it is easier for the user to determine that nightly toolchain is used and pass `--sanitizer NONE` to switch away from the nightly toolchain or install the missing toolchain.
=> Improve anyhow error handling

bolero-generator/README.md
The README example for bolero-generator is the first example one sees when exploring the package on crates.io. Updating this to reflect 0.8 avoids newcomers accidentally using an older version.
=> Change bolero-generator example to depend on 0.8

bolero-generator-derive/Cargo.toml, bolero-generator-derive/src/generator_attr.rs, bolero-generator-derive/src/lib.rs
Fixes #105
This works with both imports from bolero::generator and bolero_generator, while before people had to imperatively import from bolero_generator and explicitly use TypeGenerator.
=> do not require importing bolero_generator or TypeGenerator in order to derive

bolero/src/test/mod.rs
This makes cargo test likely to crash faster than the other way around, which in turn leads to faster iteration rate
This is a small improvement compared to #114, but always worth it even if #114 were to land
=> run crashes before corpus when running cargo test

bolero-libfuzzer/src/lib.rs, bolero/src/test/mod.rs
Without this, running `RUST_BACKTRACE=1 cargo test my_bolero_test` shows the backtrace from the internals of where cargo-bolero re-panics, but does not actually show the backtrace of where the test itself did panic
=> display backtraces on panic from cargo test

.github/workflows/main.yml
Kani now publishes an GHA action so let's use that instead.
=> ci: use official kani action

bolero/src/lib.rs
Right now as a user, I need to write `bolero::generator::gen_with()`. While this works, it would be much mork convenient to just be able to write `bolero::gen()` out-of-the-box.
(I don't think `use` statements are a good solution to that: `gen()` would be too short, unclear on where the function is coming from, and having to `use bolero::generator::gen as bolero_gen;` manually at the top of each file without rust-analyzer's help would be pretty cumbersome)
WDYT?
=> Expose functions like `bolero::gen` and `bolero::gen_with`

bolero/src/lib.rs
Hopefully closes #24.
That said somehow I haven’t been able to repro the issue today, and last time I hit it I fixed it in my code without keeping the reproducer. That said, `.with_type()` already has bounds for `Debug` and `TypeGenerator`; so the only thing that could be missing should be `Clone` for `.cloned()`.
I think even if it does not fix #24 this makes sense to merge, as it already encodes the information in a friendlier-to-rustc way than before, and does not expose a `.cloned()` method that would create an impossible-to-use `TestTarget` :)
=> Expose the `.cloned()` function only when the generator output can actually be cloned

book/src/SUMMARY.md, book/src/dev-docs/build.md, book/src/dev-docs/index.md
Starts a new section for development documentation, based on my own experience setting up the project.
It's inspired by the [Kani documentation](https://model-checking.github.io/kani/) and could be helpful for other developers looking to contribute.
=> docs: start section development documentation

bolero-generator-derive/src/generator_attr.rs, bolero-generator-derive/src/lib.rs, bolero-generator/tests/derive_test.rs
This PR fixes the macro for `#[derive(TypeGenerator)]` and resolves #121
In particular, these are the changes made:
1. Avoid adding trait bounds for non-generic types (this is what caused problems in #121).
2. Refactor code into a more functional style. The top-level function adds trait bounds, retrieves the `generate` and `mutate` methods, and emits the generated  `impl TypeGenerator for ...` at the end.
3. Add `enum` tests for the macro (with recursive variants, type parameters)
4. Add comments for most important functions and steps in the generation.
Regarding (1), it wasn't clear to me why non-generic types were added in `where` clauses. Removing the `apply_constraint` function (which did this) doesn't cause a testing regression. Trait bounds are now added to each type parameter in …
=> Fix `#[derive(TypeGenerator)]`

.github/workflows/book.yml
Deployments using the `book` workflow haven't worked for a while. This PR updates the book workflow so it's similar to [Kani's](https://github.com/model-checking/kani/blob/main/.github/workflows/kani.yml#L91). Let's see if that works.
Updates to the most recent versions for all dependencies so #94 and #125 could be closed with this one.
=> Update `book` workflow

.github/workflows/main.yml, bolero-generator-derive/src/lib.rs, bolero-generator/src/array.rs, bolero-generator/src/lib.rs, bolero-generator/tests/derive_test.rs
There were a few recent changes that broke the build in s2n-quic:
* In #126, the generic bounds in derives were changed and broke implementations using arbitrary sized arrays:
```rust
#[derive(TypeGenerator)]
struct Thing<T, const LEN: usize> {
data: [T; LEN],
}
```
This is because before we generated a where clause for the whole field type:
```rust
where [T; LEN]: TypeGenerator
```
and now we generate it just for the generic type:
```rust
where T: TypeGenerator
```
To work around this, I've implemented TypeGenerator for all array lengths, which is a good idea to do anyway.
* In #109, it was set up to prioritize importing `TypeGenerator` from the `bolero` crate, if possible. This causes issues for crates like `s2n-quic-core` where we export TypeGenerator impls with a feature flag and only …
=> fix: add generator for arbitrary sized arrays

bolero-engine/src/target_location.rs
In previous version of rustc, they would have similar behavior even in debug mode, where all the logic from a `false` evaluation would be pruned.
This is no longer true in the current rustc release candidate. I created [this thread](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/.60if.20cfg!.28false.29.60.20no.20longer.20pruned.20from.20debug.20build) to see if this was by design or if it's a bug.
That said, this is currently blocking the [Kani toolchain upgrade PR](https://github.com/model-checking/kani/pull/2406), so I was hoping we could switch the definition. Thanks!
=> Replace `if cfg!(kani)` by `#[cfg(kani)]`

Cargo.toml, Makefile, book/src/library-installation.md, cargo-bolero/src/project.rs, examples/basic/Cargo.toml, examples/workspace/Cargo.toml
Also make the default profile "fuzz", and document that it should probably have codegen-units set to 1, in replacement to the semi-fix that had been implemented only when the release mode was set.
The drawback of this change is it forces people to have a `fuzz` profile by default, and to add `codegen-units = 1` themselves. I think it is a good thing that said, because of rust’s philosophy of "better explicit than implicit" and the fact that 3 lines per crate are not too much boilerplate:
```rust
[profile.fuzz]
inherits = "release"
codegen-units = 1
debug-assertions = true # not strictly speaking necessary, but I think it’s useful
```
The big advantage is, it makes it much easier to eg. turn debug assertions on or off, and people can always use `--profile release` if they want to build in …
=> feat: replace the --release flag with a generic --profile flag 

bolero-generator/src/lib.rs, bolero-generator/src/range.rs, bolero-kani/src/lib.rs, bolero-libfuzzer/src/lib.rs
This fixes the latest clippy warnings, which are now passing: https://github.com/camshaft/bolero/actions/runs/6132949824/job/16644342393?pr=174
=> fix: address clippy warnings

bin/Cargo.toml, bin/cargo-bolero/Cargo.toml, bin/cargo-bolero/src/build_clusterfuzz.rs, bin/cargo-bolero/src/libfuzzer.rs, bin/cargo-bolero/src/list.rs, bin/cargo-bolero/src/main.rs, bin/cargo-bolero/src/project.rs, bin/cargo-bolero/src/selection.rs, bin/cargo-bolero/tests/fuzz_harnessed/fuzz_target.rs, lib/bolero-libfuzzer/src/lib.rs, tests/src/cargo_bolero.rs
This makes it very to use bolero on clusterfuzz deployments, like private ones or oss-fuzz (though I have only tested with a private deployment, not having access to an oss-fuzz-enabled project).
This builds upon #161, so please ignore the first two commits for the review. Once #161 lands I’ll rebase on top of master, but clusterfuzz requires a working -jobs option to actually work.
Fixes #98
=> Add a subcommand to build a clusterfuzz tarball

lib/bolero-engine/src/test.rs
As far as I understand unwind safety in rust, this should be safe. First
of all, because unwind "unsafety" in rust is already safe anyway, as
shown by the absence of `unsafe` keyword.
What it tries to prevent is witnessing a broken invariant in a capture,
after a panic.
Here, we replace `RefUnwindSafe` with an `AssertUnwindSafe` that is
exclusively set on a value that will never be reused after the closure
ends.
Hence, to the best of my understanding this still keeps the informal
contract of unwind safety in rust.
In practice, it allows using wasm-smith’s Arbitrary implementation with
`with_arbitrary`, without having to take bytes as arguments. Without
that, wasm-smith’s ConfiguredModule contains elements that are not
unwind safe, and would be rejected.
I would add that the error message …
=> fix: relax unwind safety requirements

lib/bolero-engine/src/shrink/tests.rs, lib/bolero-generator/src/combinator.rs, lib/bolero-generator/src/lib.rs, lib/bolero/src/lib.rs
**Breaking change**
This PR removes the `map`/`filter`/`and_then` methods from the `ValueGenerator` trait. When trying to use these methods on types that implement `Iterator` it creates conflicts that are annoying to work around:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0eac7ac05e98d4ae46bdbfe644ddb662
```rust
error[E0034]: multiple applicable items in scope
--> src/main.rs:12:20
|
12 |     let _ = (0..1).map(|v| v);
|                    ^^^ multiple `map` found
|
note: candidate #1 is defined in an impl of the trait `ValueGenerator` for the type `std::ops::Range<u64>`
--> src/main.rs:2:5
|
2  |     fn map<F>(self, f: F) -> Self {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
= note: candidate #2 is defined in an impl of the trait `Iterator` for the type …
```
=> fix(bolero-generator)!: remove map/filter/and_then to avoid conflicts with Iterator

lib/bolero-kani/src/lib.rs
We currently use `kani::assume(was_valid)` on the generator result. This isn't really what we want, since kani won't actually fail the proof if an assumption is unsatisfiable; see https://github.com/model-checking/kani/issues/2693.
Instead, the `cover!` macro is somewhat closer to what we want. It at least reports if the `was_valid` variable was ever true. Ideally, it would fail the proof so I've opened an issue for that: https://github.com/model-checking/kani/issues/2792.
=> fix(bolero-kani): use cover instead of assume

lib/bolero-engine/src/shrink.rs
I have a case where there is a 4kiB input that needs shrinking. Bolero then wants to run 4000 times the apply_transforms function before checking for shrink time.
Unfortunately, each apply_transforms seems to run my test closure 2000 times, and each test closure takes 50-100ms to run.
All together, bolero would need 9 days before checking for the shrink time limit for the first time.
With this change, bolero now checks more often the shrink time, which actually leads to me getting an error message and not what looks like a deadlock :)
----
I'll also ask, do you think you could release 0.10.1 with the fixes? It's probably not the first time I've hit the bug, but until now I've been ignoring it due to it looking like a deadlock.
=> fix: actually limit the time taken to shrink

lib/bolero-generator/src/arbitrary.rs, lib/bolero-generator/src/driver/rng.rs
Actually check for NONSENSICAL_SIZE when in DriverMode::Forced, and introduce a regression test.
=> avoid infinite loop with invalid objects

bin/cargo-bolero/src/random.rs, lib/bolero-engine/src/rng.rs, lib/bolero/src/lib.rs, lib/bolero/src/test/mod.rs, lib/bolero/src/tests.rs
I've noticed that some of my bolero tests are very unbelievably slow to run. This is because bolero runs through the whole local corpus on each run, and my tests are fundamentally slow (~10 execs / second, with a multi-thousand corpus).
My solution up to now was to have another corpus directory, but it means that I cannot use the base bolero commands, etc.
Instead, here is an idea: what if we replaced `with_iterations` with `with_test_time`? What's important for the user is the time taken by the test anyway, considering that the tests are random anyway. And computers can have vastly different speeds.
In addition, doing things this way allows setting a reasonable default test duration (1s) that's independent of how slow the tests themselves are, and that test duration will stop the tests …
=> replace with_iterations with with_test_time

lib/bolero-engine/Cargo.toml, lib/bolero-engine/src/rng.rs, lib/bolero-generator/src/uniform.rs, lib/bolero/src/test/input.rs, lib/bolero/src/test/mod.rs
We're currently using the `StdRng` for the random engine. Under the hood, this is chacha12, which is overkill for purposes of generating random inputs. This change switches the RNG implementation to use [Xoshiro256PlusPlus](https://docs.rs/rand_xoshiro/latest/rand_xoshiro/struct.Xoshiro256PlusPlus.html), which is covered in [the rand guide](https://rust-random.github.io/book/guide-rngs.html) to have a good tradeoff of speed and quality.
Additionally, I simplified the `bolero_generator::uniform::Uniform` trait implementations a bit, which should hopefully result in better coverage. Before we were branching on if we were in direct mode or not. In practice, coverage-based fuzzing engines spend a lot of time generating inputs rather than executing the tests and direct mode makes that even …
=> use a not-cryptographic rng for input generator

bin/cargo-bolero/src/libfuzzer.rs, lib/bolero-generator/src/driver/bytes.rs
In practice, branching on DriverMode being Forced/Direct in the byte slice driver doesn't result in any better signals to the fuzzing engines. This change makes the previous Forced behavior the default where zeroes are filled in at the end of the input on byte exhaustion.
=> avoid DriverMode branching on byte driver

lib/bolero-generator-derive/src/lib.rs, lib/bolero-generator/src/alloc/collections.rs, lib/bolero-generator/src/alloc/string.rs, lib/bolero-generator/src/array.rs, lib/bolero-generator/src/bounded.rs, lib/bolero-generator/src/combinator.rs, lib/bolero-generator/src/driver.rs, lib/bolero-generator/src/lib.rs, lib/bolero-generator/src/num.rs, lib/bolero-generator/src/one_of.rs, lib/bolero-generator/src/range.rs, lib/bolero-generator/src/result.rs, lib/bolero-generator/src/time.rs, lib/bolero-generator/src/tuple.rs, lib/bolero-generator/tests/derive_test.rs
This functionality extends the driver interface to allow generators to provide insights into the structure of the types being generated. This will be used to implement #203.
=> add structural methods to driver

examples/boolean-tree/src/lib.rs, lib/bolero-engine/src/noop/panic.rs, lib/bolero-engine/src/panic.rs, lib/bolero-engine/src/test.rs, lib/bolero-generator/src/driver/macros.rs
in trying to improve iteration speeds i noticed the panic functions showing up a bit. after making these changes, iteration speed has improved slightly:
```
$ cd examples/boolean-tree
$ cargo +nightly bolero test tests::model_test --engine random --sanitizer NONE
```
```
#3929088	iterations/s: 3929088
#7855104	iterations/s: 3926016
#11784192	iterations/s: 3929088
#15715328	iterations/s: 3931136
#19649536	iterations/s: 3934208
#23584768	iterations/s: 3935232
```
```
#4470784	iterations/s: 4470784
#8924160	iterations/s: 4453376
#13398016	iterations/s: 4473856
#17874944	iterations/s: 4476928
#22356992	iterations/s: 4482048
#26848256	iterations/s: 4491264
```
=> add more inlines for better optimization

lib/bolero-engine/src/lib.rs, lib/bolero-engine/src/shrink/tests.rs, lib/bolero-generator/src/arbitrary.rs, lib/bolero-generator/src/driver.rs, lib/bolero-generator/src/driver/bytes.rs, lib/bolero-generator/src/driver/macros.rs, lib/bolero-generator/src/driver/rng.rs, lib/bolero-generator/src/lib.rs, lib/bolero-generator/src/testing.rs, lib/bolero-generator/src/uniform.rs, lib/bolero-kani/src/lib.rs, lib/bolero/src/lib.rs, lib/bolero/src/test/mod.rs
Initially, DriverMode was designed to give various drivers options for how to generate values, either in Forced mode, which basically tries everything it can to generate a valid value, or `Direct` mode, which maps the underlying bytes directly to a value and bails if not possible. In practice, DriverMode is confusing, inconsistent, and poorly documented.
This change deprecates the use of `DriverMode` and instead just uses a combination of the two in places where it makes sense. Essentially, the way generators are implemented no longer depend on the driver type itself.
=> deprecate driver mode

lib/bolero-kani/Cargo.toml, lib/bolero-kani/src/lib.rs
The increase in slice size caused a few tests to OOM in the s2n-quic repo: https://github.com/aws/s2n-quic/actions/runs/9430403115/job/25977870070?pr=2233
=> revert kani slice size change

lib/bolero-kani/Cargo.toml, lib/bolero-kani/src/lib.rs
`any_vec` seems to perform much worse than a stack array slice. This change removes `any_vec` entirely.
=> kani: remove use of kani::vec::any_vec

lib/bolero-generator/src/alloc/mod.rs, lib/bolero-generator/src/alloc/string.rs, lib/bolero-generator/src/arbitrary.rs, lib/bolero-generator/src/driver/rng.rs, lib/bolero-generator/src/std/mod.rs, lib/bolero-generator/src/testing.rs
=> fix arbitrary generators

lib/bolero-generator/Cargo.toml, lib/bolero-generator/src/lib.rs, lib/bolero-generator/src/trace.rs
This change adds a utility to bolero-generator for tracing/debugging generated inputs. This can be enabled on any type that implements `ValueGenerator`:
```rust
#[derive(Debug, TypeGenerator)]
struct MyType {
field: u8,
}
check!().with_generator(gen::<MyType>().trace()).for_each(|_| { });
```
Running this will write all of the generated values to `stderr`:
```
product MyType {
u8 -> 23
}
product MyType {
u8 -> 23
}
product MyType {
u8 -> 242
}
product MyType {
u8 -> 242
}
product MyType {
u8 -> 139
}
product MyType {
u8 -> 139
}
product MyType {
u8 -> 137
}
product MyType {
u8 -> 137
}
product MyType {
u8 -> 164
}
product MyType {
u8 -> 164
}
...
```
It will also log any values that failed to return `Some` from `generate`:
```
sum EvenTree {
variant Pair {
sum EvenTree {
variant Leaf { …
```
=> feat(bolero-generator): add `trace` utility

book/src/features/structured-testing.md
=> Add book section on controlling the number of operations generated

lib/bolero-engine/src/shrink.rs, lib/bolero-engine/src/shrink/tests.rs, lib/bolero/src/test/mod.rs, lib/bolero/src/tests.rs
Fixes #248.
1. Early return `None` in `Shrinker::shrink` for zero shrink time.
2. Avoid a little bit of prep work in `TestEngine` by checking shrink time in `rng_options`.
=> Disable shrinker when `shrink_time` is zero

lib/bolero-generator/src/bounded.rs, lib/bolero-generator/src/driver.rs, lib/bolero-generator/src/driver/exhaustive.rs, lib/bolero-generator/src/driver/macros.rs, lib/bolero-generator/src/driver/rng.rs, lib/bolero-generator/src/uniform.rs, lib/bolero/src/lib.rs, lib/bolero/src/test/input.rs, lib/bolero/src/test/mod.rs, lib/bolero/src/test/report.rs, lib/bolero/src/tests.rs
This change adds an `.exhaustive()` option for harnesses, which enables the newly added `exhaustive::Driver` instead of the Rng driver.
This option, as the name implies, exhaustively searches the state space. This can be useful for state spaces that are relatively small, such as a pair of `u8`.
The exhaustive driver is based on the implementation described in https://matklad.github.io//2021/11/07/generate-all-the-things.html. The really nice thing about this implementation is it's very small and allows for a very small memory footprint - it only needs to store one chosen path at any given time.
```rust
#[test]
#[should_panic]
fn with_exhaustive_failure() {
check!()
.with_type::<(u8, u8)>()
.cloned()
.exhaustive()
.for_each(|(a, b)| {
let _ = a + b;
});
}
```
Prints:
``` …
```
=> feat(bolero-generator): add exhaustive driver

lib/bolero-generator/src/driver.rs, lib/bolero-generator/src/driver/object.rs
This change adds a object-safe trait for drivers. This will allow for things like `Box<dyn DynDriver>`, which can, for example, be stored in thread-local storage.
=> feat(bolero-generator): add DynDriver trait

lib/bolero-generator/src/alloc/string.rs, lib/bolero-generator/src/driver.rs, lib/bolero-generator/src/driver/bytes.rs, lib/bolero-generator/src/driver/exhaustive.rs, lib/bolero-generator/src/driver/macros.rs
This change adds a `bytes::Driver<T>` that takes a value that implements `AsRef<[u8]>` and turns it into a driver. This is useful for passing around owned values of a driver without having to borrow slices and worry about lifetimes.
The `ByteSliceDriver` has been refactored to use this new driver internally.
=> feat(bolero-generator): implement `bytes::Driver<T> where T: AsRef<[u8]>`

examples/basic/Cargo.toml, examples/basic/src/lib.rs, examples/boolean-tree/Cargo.toml, examples/rle-stack/Cargo.toml, lib/bolero-afl/src/lib.rs, lib/bolero-engine/Cargo.toml, lib/bolero-engine/src/any.rs, lib/bolero-engine/src/failure.rs, lib/bolero-engine/src/lib.rs, lib/bolero-engine/src/panic.rs, lib/bolero-generator/src/any/kani.rs, lib/bolero-honggfuzz/src/lib.rs, lib/bolero-kani/src/lib.rs, lib/bolero-libfuzzer/src/lib.rs, lib/bolero/Cargo.toml, lib/bolero/src/lib.rs, lib/bolero/src/test/mod.rs, lib/bolero/src/test/report.rs, lib/bolero/src/tests.rs, tests/src/engines.rs
This change adds the ability to use generator functions inside of harnesses without having to specify the inputs up front.
```rust
use bolero::*;
check!().run(|| {
let _ = any::<u64>();
let _ = (0..4).any();
let _ = [1, 2, 3].pick();
let _ = gen::<Vec<u8>>().with().len(2..4).any();
});
```
Note that there are a couple of caveats to this interface:
* This uses thread-local variables for each call to `any`, which can have a bit of overhead, so it's generally preferred to use the `.with_type` and `.with_generator` if possible
* The harness does not currently track inputs for displaying when things fail so it may be a bit more difficult to debug. This may change in the future.
* Shrinking is currently not implemented but will be at a later time.
=> feat: add `run` interface

bin/cargo-bolero/src/random.rs, lib/bolero-engine/Cargo.toml, lib/bolero-generator/Cargo.toml, lib/bolero-generator/src/any/default.rs, lib/bolero-generator/src/driver.rs, lib/bolero-generator/src/driver/bytes.rs, lib/bolero-generator/src/driver/cache.rs, lib/bolero-generator/src/driver/exhaustive.rs, lib/bolero-generator/src/driver/object.rs, lib/bolero-generator/src/driver/rng.rs, lib/bolero-generator/src/lib.rs, lib/bolero-generator/src/result.rs, lib/bolero-generator/src/testing.rs, lib/bolero-generator/src/trace.rs, lib/bolero/Cargo.toml, lib/bolero/src/lib.rs, lib/bolero/src/test/input.rs, lib/bolero/src/test/mod.rs, lib/bolero/src/test/report.rs
Update `rand` requirement in Bolero to unblock `bach` and `s2n-quic` rand updates.
I have updated the versions for `rand`, `rand_xoshiro`, and `getrandom` versions to be the most up to date versions. In the new version of `rand`, `try_fill_bytes()` trait has been removed, so I have removed those from Bolero accordingly. `alloc` is fully removed from `rand_core`, so we don't pull `alloc` from `rand_core`. Most of changes are reflecting recent renames in those dependencies.
We are updating these requirements to unlock `s2n-quic`'s rand updates. A tracking issue can be found in this link: https://github.com/aws/s2n-quic/issues/2479.
* In `rand v0.9.0`, the original `RngCore` is split into two traits. Here is the [doc](https://rust-random.github.io/book/update-0.9.html#core-traits). Here is …
=> build(deps): update rand, rand_xoshiro, and getrandom requirements

bin/cargo-bolero/Cargo.toml, lib/bolero-afl/Cargo.toml, lib/bolero-engine/Cargo.toml, lib/bolero-generator-derive/Cargo.toml, lib/bolero-generator/Cargo.toml, lib/bolero-honggfuzz/Cargo.toml, lib/bolero-kani/Cargo.toml, lib/bolero-libfuzzer/Cargo.toml, lib/bolero/Cargo.toml
Bolero v0.13.0 release.
This is a step in https://github.com/aws/s2n-quic/issues/2479.
=> chore: release 0.13.0

bin/cargo-bolero/src/project.rs
Without this, I'm getting the following error on my production system:
```
Undefined symbols for architecture arm64:
"___getrandom_custom", referenced from:
getrandom::custom::getrandom_inner::he09b0ce5a718e198 in libgetrandom-de720050bd3ff58d.rlib[3](getrandom-de720050bd3ff58d.getrandom.67592e623299eaa1-cgu.0.rcgu.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I couldn't find motivation for this specific flag, so I'm suggesting this change to just remove it. As always, thank you for your work on bolero! 😄
=> fix: remove link-dead-code, that causes linker failures on macos

lib/bolero-generator-derive/src/lib.rs
For reasons ™, we link bolero_generator against a target crate using the rustc flag `--extern`. This breaks the derive macro because it expects to find either `bolero` or `bolero_generator` in Cargo.toml. This PR defaults to using the crate name `bolero_generator` instead of panicking when we can't find bolero in Cargo.toml.
=> Fallback to `::bolero_generator` as crate name in derive macro

lib/bolero-engine/src/target_location.rs, lib/bolero/src/test/mod.rs, lib/bolero/src/test/outcome.rs
=> feat: print test outcome on exit

lib/bolero-engine/Cargo.toml, lib/bolero-engine/src/panic.rs
Discussed offline with @camshaft, we should use standard backtrace for `bolero-engine`, so that we can remove our dependency on `backtrace-rs`: https://github.com/camshaft/bolero/pull/282#issuecomment-2860040487.
This PR resolves https://github.com/camshaft/bolero/pull/282.
Please review if I fully clean up the customized backtrace structs and its impls.
Use bolero CI to test it.
=> refactor(bolero-engine): use standard Backtrace instead of backtrace-rs

bin/cargo-bolero/Cargo.toml, lib/bolero-afl/Cargo.toml, lib/bolero-engine/Cargo.toml, lib/bolero-generator-derive/Cargo.toml, lib/bolero-generator/Cargo.toml, lib/bolero-honggfuzz/Cargo.toml, lib/bolero-kani/Cargo.toml, lib/bolero-libfuzzer/Cargo.toml, lib/bolero/Cargo.toml
Patch release for Bolero. Version bumps to v0.13.3.
I followed the previous release PR: https://github.com/camshaft/bolero/pull/281.
Please check if those are the only crates that needs to be released.
=> chore: release v0.13.3

bin/cargo-bolero/src/project.rs
We need to pass the `--workspace` flag to `cargo test` in order to eg. list all fuzzers in https://github.com/agglayer/agglayer
=> feat: allow listing the whole workspace

bin/cargo-bolero/src/libfuzzer.rs, examples/reduce/Cargo.toml, examples/reduce/src/lib.rs, tests/src/main.rs, tests/src/reduce.rs
The reduce command currently doesn't remove redundant inputs in the corpus (see #247). This PR fixes it.
Keeping this as a draft till I add a test.
=> Fix reduce command
